# MAIN base
baseURL = "https://gofeatureflag.org/"
languageCode = "en-us"
title = "GO Feature Flag"
theme = "apsho"

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = "#hero"
    weight = 1
[[menu.main]]
    name = "About"
    url = "#feature"
    weight = 2
[[menu.main]]
    name = "Why"
    url = "#benefits"
    weight = 3
[[menu.main]]
    name = "Documentation"
    url = "https://docs.gofeatureflag.org"
    weight = 4
[[menu.main]]
    name = "Editor"
    url = "https://editor.gofeatureflag.org"
    weight = 5

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Latest Article"
    url = "/blog"
    weight = 2
# [[menu.sitemap]]
#     name = "Privacy & Policy"
#     url = "/privacy"
#     weight = 3
[[menu.sitemap]]
    name = "Contact"
    url = "/contact"
    weight = 4

# Footer Address
[params.address]
address = "Paris, France"
email = "contact@gofeatureflag.org"

# Footer Social
[params.social]
twitter = "https://twitter.com/go-feature-flag"
github = "https://github.com/thomaspoignant"

[params]

# Header
logo = "images/logo.png"
formspreeURL = "https://formspree.io/f/xqknoogk"
googleAnalytics = "G-YMBZZ2GYSK"

# Footer
footerTitle = "Get the latest app updates"
copyright1 = "All right reserved"
copyright2 = "© GO-feature-flag {year}"

#contact
email = "contact@gofeatureflag.org"
